name: E2E DB (optional)

on:
  workflow_dispatch:
    inputs:
      seed:
        description: 'Run seed after db push'
        required: false
        default: 'false'

jobs:
  e2e-db:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:./prisma/e2e.db
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prisma DB push (skip generate)
        run: npx prisma db push --skip-generate

      - name: Seed database (optional)
        if: ${{ inputs.seed == 'true' }}
        run: pnpm run db:seed
