name: Preview Deploy

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  deployments: write

jobs:
  preview:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
      # DATABASE_URL can be set to a lightweight sqlite db for previews if needed
      # DATABASE_URL: file:./prisma/dev.db
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm run db:generate

      - name: Build Next.js
        run: pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next
            package.json
            next.config.mjs
            pnpm-lock.yaml
            pnpm-workspace.yaml
            .vercel/**

      - name: Vercel Deploy (Preview)
        uses: vercel/action@v3
        if: ${{ success() }}
        with:
          working-directory: .
          # Configure these repository secrets in GitHub settings:
          # VERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_ID
          token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          production: false
